import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np
import torch
import torchvision.transforms as transforms
import shutil

# Import your models and preprocessing configuration
from models import AdvancedUNetGenerator
from preprocess import Config, render_char

# Use academic paper-level chart style
plt.style.use('seaborn-v0_8-paper')

def smooth_curve(values, window=5):
    return values.rolling(window=window, center=True, min_periods=1).median()

def set_stable_ylim(ax, values, pad=0.12):
    vmin = float(values.min())
    vmax = float(values.max())
    if np.isclose(vmin, vmax):
        margin = max(0.05, abs(vmin) * pad)
    else:
        margin = (vmax - vmin) * pad
    ax.set_ylim(vmin - margin, vmax + margin)

def save_academic_plots():
    os.makedirs('Analysis_Plots', exist_ok=True)
    for filename in os.listdir('Analysis_Plots'):
        if filename.endswith('.png'):
            os.remove(os.path.join('Analysis_Plots', filename))
    
    # Perfectly align with the 5 task logs automatically generated by train.py
    files = {
        'baseline': 'train_log_Task1_Baseline.csv',
        'ablation': 'train_log_Task2_Ablation.csv',
        'vae': 'train_log_Task3_VAE.csv',
        'gan_l1': 'train_log_Task4_GAN_L1.csv',
        'gan_l2': 'train_log_Task5_GAN_L2.csv'
    }

    print("[*] Plotting academic-grade learning curves (Metrics: L1, L2, L_adv, L_KL)...")

    # Plot 1: Factor I - Baseline U-Net Execution ($L_1$ Loss)
    if os.path.exists(files['baseline']):
        df_base = pd.read_csv(files['baseline'])

        plt.figure(figsize=(8, 5))
        plt.plot(
            df_base['Epoch'],
            df_base['L1_Recon_Loss'],
            label='Baseline U-Net (w/ Skip-Conn, $L_1$)',
            color='#1f77b4',
            linewidth=2
        )
        plt.title('Factor I: Baseline U-Net Training Progress', fontsize=12, fontweight='bold')
        plt.xlabel('Epoch')
        plt.ylabel('$L_1$ Reconstruction Loss')
        plt.xlim(0, df_base['Epoch'].max())
        plt.ylim(bottom=0)
        plt.legend()
        plt.grid(True, linestyle=':', alpha=0.7)
        plt.tight_layout()
        plt.savefig('Analysis_Plots/1_Factor1_Baseline_Execution.png', dpi=300)
        plt.close()

    # Plot 2: Factor II - Skip-Connections Ablation Study ($L_1$ Loss)
    if os.path.exists(files['baseline']) and os.path.exists(files['ablation']):
        df_base = pd.read_csv(files['baseline'])
        df_abl = pd.read_csv(files['ablation'])
        
        plt.figure(figsize=(8, 5))
        plt.plot(df_base['Epoch'], df_base['L1_Recon_Loss'], label='U-Net (w/ Skip-Conn, $L_1$)', color='#1f77b4', linewidth=2)
        plt.plot(df_abl['Epoch'], df_abl['L1_Recon_Loss'], label='Bottleneck (w/o Skip-Conn, $L_1$)', color='#ff7f0e', linewidth=2, linestyle='--')
        
        plt.title('Factor II: Impact of Skip-Connections on $L_1$ Reconstruction', fontsize=12, fontweight='bold')
        plt.xlabel('Epoch'); plt.ylabel('$L_1$ Loss Value')
        
        # Force X and Y axes to start exactly at 0
        plt.xlim(0, df_base['Epoch'].max())
        plt.ylim(bottom=0)
        
        plt.legend(); plt.grid(True, linestyle=':', alpha=0.7)
        plt.tight_layout()
        plt.savefig('Analysis_Plots/2_Factor2_Ablation.png', dpi=300); plt.close()

    # Plot 3: Factor III - VAE Latent Space Regularization ($L_1$ vs $L_{KL}$)
    if os.path.exists(files['vae']):
        df_vae = pd.read_csv(files['vae'])
        fig, ax1 = plt.subplots(figsize=(8, 5))
        
        ax1.set_xlabel('Epoch')
        ax1.set_ylabel('$L_1$ Recon Loss', color='#1f77b4')
        ax1.plot(df_vae['Epoch'], df_vae['L1_Recon_Loss'], color='#1f77b4', label='$L_1$ Loss', linewidth=2)
        
        ax2 = ax1.twinx()  
        ax2.set_ylabel('$L_{KL}$ (KL Divergence Loss)', color='#2ca02c')
        ax2.plot(df_vae['Epoch'], df_vae['KL_Loss'], color='#2ca02c', label='$L_{KL}$', linewidth=2, linestyle='-.')
        
        plt.axvspan(0, 50, color='gray', alpha=0.1, label='KL Annealing Phase')
        
        # Force the bottom of both Y axes and the start of X axis to exactly 0
        ax1.set_xlim(0, df_vae['Epoch'].max())
        ax1.set_ylim(bottom=0)
        ax2.set_ylim(bottom=0)
        
        plt.title('Factor III: VAE Convergence with $L_{KL}$ Annealing', fontsize=12, fontweight='bold')
        fig.tight_layout(); plt.grid(True, linestyle=':', alpha=0.7)
        plt.savefig('Analysis_Plots/3_Factor3_VAE_Dynamics.png', dpi=300); plt.close()

    # Plot 4: Factor IV - WGAN-GP Adversarial Training Diagnostics
    if os.path.exists(files['gan_l1']):
        df_gan = pd.read_csv(files['gan_l1'])
        recon_smooth = smooth_curve(df_gan['L1_Recon_Loss'])
        d_loss_smooth = smooth_curve(df_gan['D_Loss'])
        g_adv_smooth = smooth_curve(df_gan['G_Adv_Loss'])
        
        fig, (ax0, ax1, ax2) = plt.subplots(3, 1, figsize=(8, 10), sharex=True)

        # --- Top Plot: Reconstruction loss, the monotonic convergence indicator ---
        ax0.plot(
            df_gan['Epoch'],
            recon_smooth,
            color='#1f77b4',
            label='$L_1$ reconstruction (5-epoch rolling median)',
            linewidth=2.0
        )
        ax0.set_ylabel('$L_1$ Recon Loss', color='#1f77b4', fontsize=11)
        ax0.set_title('Factor IV: Reconstruction Convergence under GAN Training', fontsize=12, fontweight='bold')
        ax0.grid(True, linestyle=':', alpha=0.7)
        ax0.legend(loc='upper right')
        ax0.set_xlim(left=0, right=df_gan['Epoch'].max())
        ax0.set_ylim(bottom=0, top=float(recon_smooth.max()) * 1.15)
        
        # --- Middle Plot: Discriminator critic signal ---
        ax1.plot(
            df_gan['Epoch'],
            d_loss_smooth,
            color='#9467bd',
            label='Critic signal $D_{loss}$ (5-epoch rolling median)',
            linewidth=2.0
        )
        ax1.axhline(0, color='#666666', linewidth=0.8, alpha=0.6)
        ax1.set_ylabel('Critic Signal', color='#9467bd', fontsize=11)
        ax1.set_title('Factor IV: WGAN-GP Critic Balance', fontsize=12, fontweight='bold')
        ax1.grid(True, linestyle=':', alpha=0.7)
        ax1.legend(loc='upper right')
        ax1.set_xlim(left=0, right=df_gan['Epoch'].max())
        set_stable_ylim(ax1, d_loss_smooth)
        
        # --- Bottom Plot: Generator adversarial signal ---
        ax2.plot(
            df_gan['Epoch'],
            g_adv_smooth,
            color='#d62728',
            label='Generator adversarial signal $L_{adv}$ (5-epoch rolling median)',
            linewidth=2.0,
            linestyle='-.'
        )
        ax2.axhline(0, color='#666666', linewidth=0.8, alpha=0.6)
        ax2.set_xlabel('Epoch')
        ax2.set_ylabel('$L_{adv}$ Signal', color='#d62728', fontsize=11)
        ax2.set_title('Factor IV: Generator Adversarial Feedback', fontsize=12, fontweight='bold')
        ax2.grid(True, linestyle=':', alpha=0.7)
        ax2.legend(loc='upper right')
        ax2.set_xlim(left=0, right=df_gan['Epoch'].max())
        set_stable_ylim(ax2, g_adv_smooth)
        
        fig.text(
            0.5,
            0.045,
            'WGAN-GP signals are diagnostic; convergence is judged by lower reconstruction loss and bounded critic feedback.',
            ha='center',
            fontsize=9
        )
        fig.tight_layout()
        fig.subplots_adjust(bottom=0.12)
        plt.savefig('Analysis_Plots/4_Factor4_GAN_Diagnostics.png', dpi=300)
        plt.close()

    # Plot 5: Factor V - Objective Function Comparison (L_1 vs L_2)
    if os.path.exists(files['gan_l1']) and os.path.exists(files['gan_l2']):
        df_g1 = pd.read_csv(files['gan_l1'])
        df_g2 = pd.read_csv(files['gan_l2'])
        plt.figure(figsize=(8, 5))
        min_len = min(len(df_g1), len(df_g2))
        
        plt.plot(df_g1['Epoch'][:min_len], df_g1['L1_Recon_Loss'][:min_len], label='$L_1$ (MAE) Optimization', color='#17becf', linewidth=2)
        plt.plot(df_g2['Epoch'][:min_len], df_g2['L2_Recon_Loss'][:min_len], label='$L_2$ (MSE) Optimization', color='#e377c2', linewidth=2, linestyle='--')
        
        plt.title('Factor V: Comparison of Objective Functions ($L_1$ vs $L_2$)', fontsize=12, fontweight='bold')
        plt.xlabel('Epoch'); plt.ylabel('Loss Value')
        
        # Force X and Y axes to start exactly at 0
        plt.xlim(0, min_len)
        plt.ylim(bottom=0)
        
        plt.legend(); plt.grid(True, linestyle=':', alpha=0.7)
        plt.tight_layout()
        plt.savefig('Analysis_Plots/5_Factor5_L1_vs_L2.png', dpi=300); plt.close()

def export_final_tang_poem_plot():
    if not os.path.exists('best_model_config.txt'):
        return

    with open('best_model_config.txt', 'r', encoding='utf-8') as f:
        best_task = f.read().strip()

    candidates = [
        f'BEST_TangPoem_FinalSelection_{best_task}.png',
        f'TangPoem_Matrix_by_{best_task}.png',
    ]

    for src in candidates:
        if os.path.exists(src):
            dst = f'Analysis_Plots/6_Factor6_TangPoem_FinalSelection_{best_task}.png'
            shutil.copyfile(src, dst)
            print(f"[+] Final Tang poem selection copied to {dst}")
            return

# ==========================================
# Module 2: Visual Quality Analysis Comparison Matrix (Factor VI Evidence)
# ==========================================
def generate_visual_quality_analysis():
    print("[*] Generating Visual Quality Analysis plots...")
    device = torch.device("cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu"))
    TASK_CONFIGS = {    
        "Task1_Baseline": {"skip": True,  "vae": False, "compress": False},
        # 👇 Just change compress to False on this line to match your latest actual weights 100%!
        "Task2_Ablation": {"skip": False, "vae": False, "compress": False}, 
        "Task3_VAE":      {"skip": True,  "vae": True,  "compress": False},
        "Task4_GAN_L1":   {"skip": True,  "vae": False, "compress": False},
        "Task5_GAN_L2":   {"skip": True,  "vae": False, "compress": False}
    }

    test_char = "永"  # Use the classic Yong character for final visual-quality comparison
    transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.5], [0.5])])
    src_img = render_char(test_char, Config.SOURCE_FONT)
    src_tensor = transform(src_img).unsqueeze(0).to(device)
    style_label = torch.tensor([0]).to(device) # Test style 0

    fig, axes = plt.subplots(1, 6, figsize=(18, 3))
    axes[0].imshow(src_img, cmap='gray'); axes[0].set_title("Source (GT)", fontweight='bold'); axes[0].axis('off')

    for idx, (task_name, cfg) in enumerate(TASK_CONFIGS.items()):
        ax = axes[idx + 1]
        weight_path = f"weights_{task_name}/generator_epoch_100.pth"
        
        if os.path.exists(weight_path):
            gen = AdvancedUNetGenerator(1, 1, 5, cfg['skip'], cfg['vae'], cfg['compress']).to(device)
            gen.load_state_dict(torch.load(weight_path, map_location=device))
            gen.eval()
            with torch.no_grad():
                fake, _ = gen(src_tensor, style_label)
            img = np.clip((fake.squeeze().cpu().numpy() * 0.5 + 0.5) * 255, 0, 255).astype(np.uint8)
            ax.imshow(img, cmap='gray')
            ax.set_title(task_name.split('_')[-1], fontsize=11, fontweight='bold')
        else:
            ax.text(0.5, 0.5, 'N/A', ha='center')
        ax.axis('off')

    plt.tight_layout()
    plt.savefig('Analysis_Plots/7_Supporting_Visual_Quality_Analysis.png', dpi=300)
    plt.close()
    print("[+] Visual comparison plots generated successfully.")

def generate_checkpoint_model_comparisons():
    print("[*] Generating checkpoint visual evolution across all five models...")
    os.makedirs('Analysis_Plots', exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu"))
    task_configs = {
        "Task1_Baseline": {"label": "Baseline", "skip": True,  "vae": False, "compress": False},
        "Task2_Ablation": {"label": "Ablation", "skip": False, "vae": False, "compress": False},
        "Task3_VAE":      {"label": "VAE",      "skip": True,  "vae": True,  "compress": False},
        "Task4_GAN_L1":   {"label": "L1",       "skip": True,  "vae": False, "compress": False},
        "Task5_GAN_L2":   {"label": "L2",       "skip": True,  "vae": False, "compress": False},
    }
    checkpoint_outputs = {
        30: "Analysis_Plots/8_Factor7_Checkpoint_Epoch30_ModelComparison.png",
        60: "Analysis_Plots/9_Factor7_Checkpoint_Epoch60_ModelComparison.png",
        100: "Analysis_Plots/10_Factor7_Checkpoint_Epoch100_ModelComparison.png",
    }

    test_char = "永"
    transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.5], [0.5])])
    src_img = render_char(test_char, Config.SOURCE_FONT)
    src_tensor = transform(src_img).unsqueeze(0).to(device)
    style_label = torch.tensor([0], dtype=torch.long).to(device)

    for epoch, output_path in checkpoint_outputs.items():
        fig, axes = plt.subplots(1, 6, figsize=(18, 3))
        axes[0].imshow(src_img, cmap='gray')
        axes[0].set_title("Source (GT)", fontweight='bold')
        axes[0].axis('off')

        for idx, (task_name, cfg) in enumerate(task_configs.items(), start=1):
            ax = axes[idx]
            weight_path = f"weights_{task_name}/generator_epoch_{epoch}.pth"
            if os.path.exists(weight_path):
                torch.manual_seed(2575736)
                gen = AdvancedUNetGenerator(1, 1, 5, cfg['skip'], cfg['vae'], cfg['compress']).to(device)
                gen.load_state_dict(torch.load(weight_path, map_location=device))
                gen.eval()
                with torch.no_grad():
                    fake, _ = gen(src_tensor, style_label)
                img = np.clip((fake.squeeze().cpu().numpy() * 0.5 + 0.5) * 255, 0, 255).astype(np.uint8)
                ax.imshow(img, cmap='gray')
            else:
                ax.text(0.5, 0.5, 'N/A', ha='center', va='center')

            ax.set_title(cfg['label'], fontsize=11, fontweight='bold')
            ax.axis('off')

        fig.suptitle(f"Checkpoint Visual Evolution at {epoch}% Training Progress", fontsize=13, fontweight='bold')
        plt.tight_layout()
        plt.subplots_adjust(top=0.82)
        plt.savefig(output_path, dpi=300)
        plt.close()
        print(f"[+] Saved {output_path}")

if __name__ == "__main__":
    save_academic_plots()
    export_final_tang_poem_plot()
    try:
        generate_visual_quality_analysis()
    except Exception as e:
        print(f"[!] Visual generation failed (ensure weight files exist): {e}")
    try:
        generate_checkpoint_model_comparisons()
    except Exception as e:
        print(f"[!] Checkpoint comparison generation failed: {e}")
    print("\n[+] All required plots for Factor I-VI have been saved to 'Analysis_Plots'.")
